// <auto-generated />
// 💡【教學：什麼是 Compiled Models (預先編譯模型)？】
// 在標準的 EF Core 應用中，DbContext 啟動時會透過反射 (Reflection) 動態掃描所有的 Model 
// (如 OracleDemoItem)，然後在記憶體中建立模型結構 (IModel)。
// 
// 但是！我們的專案啟用了 Native AOT (<PublishAot>true</PublishAot>)。
// Native AOT 環境「不支援動態反射與程式碼產生」，因此如果讓 EF Core 在執行期動態掃描，
// 應用程式一啟動就會崩潰！
// 
// 💡【解決方案：編譯期產生模型】
// 我們透過在終端機執行 `dotnet ef dbcontext optimize -c AppDbContext -o CompiledModels --nativeaot`，
// 讓 EF Core CLI 在「開發階段」就提早把所有資料庫的對應關係寫死成靜態 C# 程式碼 (就在這個資料夾裡)。
// 然後我們在 Program.cs 中使用 `options.UseModel(AppDbContextModel.Instance)`，
// 這樣 EF Core 啟動時就能直接載入這個靜態模型，完全不需要反射，完美支援 Native AOT 且啟動速度極快！
using DotNetMinimalAPI.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DotNetMinimalAPI.CompiledModels
{
    [DbContext(typeof(AppDbContext))]
    public partial class AppDbContextModel : RuntimeModel
    {
        private static readonly bool _useOldBehavior31751 =
            System.AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue31751", out var enabled31751) && enabled31751;

        static AppDbContextModel()
        {
            var model = new AppDbContextModel();

            if (_useOldBehavior31751)
            {
                model.Initialize();
            }
            else
            {
                var thread = new System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
                thread.Start();
                thread.Join();

                void RunInitialization()
                {
                    model.Initialize();
                }
            }

            model.Customize();
            _instance = (AppDbContextModel)model.FinalizeModel();
        }

        private static AppDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
