// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;
using Oracle.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DotNetMinimalAPI.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("a52857c8-cc16-4dd7-b005-7f6a600043ae"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var oracleDemoCategory = OracleDemoCategoryEntityType.Create(this);
            var oracleDemoItem = OracleDemoItemEntityType.Create(this);

            OracleDemoItemEntityType.CreateForeignKey1(oracleDemoItem, oracleDemoCategory);

            OracleDemoCategoryEntityType.CreateAnnotations(oracleDemoCategory);
            OracleDemoItemEntityType.CreateAnnotations(oracleDemoItem);

            AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var oracleDemoCategory = FindEntityType("DotNetMinimalAPI.Models.OracleDemoCategory")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            oracleDemoCategory.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var dotNetMinimalAPIModelsOracleDemoCategoryTableBase = new TableBase("DotNetMinimalAPI.Models.OracleDemoCategory", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "TIMESTAMP(7)", dotNetMinimalAPIModelsOracleDemoCategoryTableBase);
            dotNetMinimalAPIModelsOracleDemoCategoryTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "NUMBER(10)", dotNetMinimalAPIModelsOracleDemoCategoryTableBase);
            dotNetMinimalAPIModelsOracleDemoCategoryTableBase.Columns.Add("Id", idColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "NVARCHAR2(2000)", dotNetMinimalAPIModelsOracleDemoCategoryTableBase);
            dotNetMinimalAPIModelsOracleDemoCategoryTableBase.Columns.Add("Name", nameColumnBase);
            relationalModel.DefaultTables.Add("DotNetMinimalAPI.Models.OracleDemoCategory", dotNetMinimalAPIModelsOracleDemoCategoryTableBase);
            var dotNetMinimalAPIModelsOracleDemoCategoryMappingBase = new TableMappingBase<ColumnMappingBase>(oracleDemoCategory, dotNetMinimalAPIModelsOracleDemoCategoryTableBase, null);
            dotNetMinimalAPIModelsOracleDemoCategoryTableBase.AddTypeMapping(dotNetMinimalAPIModelsOracleDemoCategoryMappingBase, false);
            defaultTableMappings.Add(dotNetMinimalAPIModelsOracleDemoCategoryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, oracleDemoCategory.FindProperty("Id")!, dotNetMinimalAPIModelsOracleDemoCategoryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, oracleDemoCategory.FindProperty("CreatedAt")!, dotNetMinimalAPIModelsOracleDemoCategoryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, oracleDemoCategory.FindProperty("Name")!, dotNetMinimalAPIModelsOracleDemoCategoryMappingBase);

            var tableMappings = new List<TableMapping>();
            oracleDemoCategory.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var oracleDemoCategoriesTable = new Table("OracleDemoCategories", null, relationalModel);
            var idColumn = new Column("Id", "NUMBER(10)", oracleDemoCategoriesTable);
            oracleDemoCategoriesTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            idColumn.AddAnnotation("Oracle:Identity", "START WITH 1 INCREMENT BY 1");
            var createdAtColumn = new Column("CreatedAt", "TIMESTAMP(7)", oracleDemoCategoriesTable);
            oracleDemoCategoriesTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn);
            var nameColumn = new Column("Name", "NVARCHAR2(2000)", oracleDemoCategoriesTable);
            oracleDemoCategoriesTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            relationalModel.Tables.Add(("OracleDemoCategories", null), oracleDemoCategoriesTable);
            var oracleDemoCategoriesTableMapping = new TableMapping(oracleDemoCategory, oracleDemoCategoriesTable, null);
            oracleDemoCategoriesTable.AddTypeMapping(oracleDemoCategoriesTableMapping, false);
            tableMappings.Add(oracleDemoCategoriesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, oracleDemoCategory.FindProperty("Id")!, oracleDemoCategoriesTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, oracleDemoCategory.FindProperty("CreatedAt")!, oracleDemoCategoriesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, oracleDemoCategory.FindProperty("Name")!, oracleDemoCategoriesTableMapping);
            var pK_OracleDemoCategories = new UniqueConstraint("PK_OracleDemoCategories", oracleDemoCategoriesTable, new[] { idColumn });
            oracleDemoCategoriesTable.PrimaryKey = pK_OracleDemoCategories;
            pK_OracleDemoCategories.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_OracleDemoCategories));
            var pK_OracleDemoCategoriesKey = RelationalModel.GetKey(this,
                "DotNetMinimalAPI.Models.OracleDemoCategory",
                new[] { "Id" });
            pK_OracleDemoCategories.MappedKeys.Add(pK_OracleDemoCategoriesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_OracleDemoCategoriesKey).Add(pK_OracleDemoCategories);
            oracleDemoCategoriesTable.UniqueConstraints.Add("PK_OracleDemoCategories", pK_OracleDemoCategories);

            var oracleDemoItem = FindEntityType("DotNetMinimalAPI.Models.OracleDemoItem")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            oracleDemoItem.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var dotNetMinimalAPIModelsOracleDemoItemTableBase = new TableBase("DotNetMinimalAPI.Models.OracleDemoItem", null, relationalModel);
            var categoryIdColumnBase = new ColumnBase<ColumnMappingBase>("CategoryId", "NUMBER(10)", dotNetMinimalAPIModelsOracleDemoItemTableBase)
            {
                IsNullable = true
            };
            dotNetMinimalAPIModelsOracleDemoItemTableBase.Columns.Add("CategoryId", categoryIdColumnBase);
            var createdAtColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedAt", "TIMESTAMP(7)", dotNetMinimalAPIModelsOracleDemoItemTableBase);
            dotNetMinimalAPIModelsOracleDemoItemTableBase.Columns.Add("CreatedAt", createdAtColumnBase0);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "NVARCHAR2(2000)", dotNetMinimalAPIModelsOracleDemoItemTableBase)
            {
                IsNullable = true
            };
            dotNetMinimalAPIModelsOracleDemoItemTableBase.Columns.Add("Description", descriptionColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "NUMBER(10)", dotNetMinimalAPIModelsOracleDemoItemTableBase);
            dotNetMinimalAPIModelsOracleDemoItemTableBase.Columns.Add("Id", idColumnBase0);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "NVARCHAR2(2000)", dotNetMinimalAPIModelsOracleDemoItemTableBase);
            dotNetMinimalAPIModelsOracleDemoItemTableBase.Columns.Add("Name", nameColumnBase0);
            relationalModel.DefaultTables.Add("DotNetMinimalAPI.Models.OracleDemoItem", dotNetMinimalAPIModelsOracleDemoItemTableBase);
            var dotNetMinimalAPIModelsOracleDemoItemMappingBase = new TableMappingBase<ColumnMappingBase>(oracleDemoItem, dotNetMinimalAPIModelsOracleDemoItemTableBase, null);
            dotNetMinimalAPIModelsOracleDemoItemTableBase.AddTypeMapping(dotNetMinimalAPIModelsOracleDemoItemMappingBase, false);
            defaultTableMappings0.Add(dotNetMinimalAPIModelsOracleDemoItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, oracleDemoItem.FindProperty("Id")!, dotNetMinimalAPIModelsOracleDemoItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)categoryIdColumnBase, oracleDemoItem.FindProperty("CategoryId")!, dotNetMinimalAPIModelsOracleDemoItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase0, oracleDemoItem.FindProperty("CreatedAt")!, dotNetMinimalAPIModelsOracleDemoItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, oracleDemoItem.FindProperty("Description")!, dotNetMinimalAPIModelsOracleDemoItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, oracleDemoItem.FindProperty("Name")!, dotNetMinimalAPIModelsOracleDemoItemMappingBase);

            var tableMappings0 = new List<TableMapping>();
            oracleDemoItem.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var oracleDemoItemsTable = new Table("OracleDemoItems", null, relationalModel);
            var idColumn0 = new Column("Id", "NUMBER(10)", oracleDemoItemsTable);
            oracleDemoItemsTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn0);
            idColumn0.AddAnnotation("Oracle:Identity", "START WITH 1 INCREMENT BY 1");
            var categoryIdColumn = new Column("CategoryId", "NUMBER(10)", oracleDemoItemsTable)
            {
                IsNullable = true
            };
            oracleDemoItemsTable.Columns.Add("CategoryId", categoryIdColumn);
            categoryIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(categoryIdColumn);
            var createdAtColumn0 = new Column("CreatedAt", "TIMESTAMP(7)", oracleDemoItemsTable);
            oracleDemoItemsTable.Columns.Add("CreatedAt", createdAtColumn0);
            createdAtColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn0);
            var descriptionColumn = new Column("Description", "NVARCHAR2(2000)", oracleDemoItemsTable)
            {
                IsNullable = true
            };
            oracleDemoItemsTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var nameColumn0 = new Column("Name", "NVARCHAR2(2000)", oracleDemoItemsTable);
            oracleDemoItemsTable.Columns.Add("Name", nameColumn0);
            nameColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn0);
            relationalModel.Tables.Add(("OracleDemoItems", null), oracleDemoItemsTable);
            var oracleDemoItemsTableMapping = new TableMapping(oracleDemoItem, oracleDemoItemsTable, null);
            oracleDemoItemsTable.AddTypeMapping(oracleDemoItemsTableMapping, false);
            tableMappings0.Add(oracleDemoItemsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, oracleDemoItem.FindProperty("Id")!, oracleDemoItemsTableMapping);
            RelationalModel.CreateColumnMapping(categoryIdColumn, oracleDemoItem.FindProperty("CategoryId")!, oracleDemoItemsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn0, oracleDemoItem.FindProperty("CreatedAt")!, oracleDemoItemsTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, oracleDemoItem.FindProperty("Description")!, oracleDemoItemsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, oracleDemoItem.FindProperty("Name")!, oracleDemoItemsTableMapping);
            var pK_OracleDemoItems = new UniqueConstraint("PK_OracleDemoItems", oracleDemoItemsTable, new[] { idColumn0 });
            oracleDemoItemsTable.PrimaryKey = pK_OracleDemoItems;
            pK_OracleDemoItems.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_OracleDemoItems));
            var pK_OracleDemoItemsKey = RelationalModel.GetKey(this,
                "DotNetMinimalAPI.Models.OracleDemoItem",
                new[] { "Id" });
            pK_OracleDemoItems.MappedKeys.Add(pK_OracleDemoItemsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_OracleDemoItemsKey).Add(pK_OracleDemoItems);
            oracleDemoItemsTable.UniqueConstraints.Add("PK_OracleDemoItems", pK_OracleDemoItems);
            var iX_OracleDemoItems_CategoryId = new TableIndex(
            "IX_OracleDemoItems_CategoryId", oracleDemoItemsTable, new[] { categoryIdColumn }, false);
            iX_OracleDemoItems_CategoryId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<int>(iX_OracleDemoItems_CategoryId));
            var iX_OracleDemoItems_CategoryIdIx = RelationalModel.GetIndex(this,
                "DotNetMinimalAPI.Models.OracleDemoItem",
                new[] { "CategoryId" });
            iX_OracleDemoItems_CategoryId.MappedIndexes.Add(iX_OracleDemoItems_CategoryIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_OracleDemoItems_CategoryIdIx).Add(iX_OracleDemoItems_CategoryId);
            oracleDemoItemsTable.Indexes.Add("IX_OracleDemoItems_CategoryId", iX_OracleDemoItems_CategoryId);
            var fK_OracleDemoItems_OracleDemoCategories_CategoryId = new ForeignKeyConstraint(
                "FK_OracleDemoItems_OracleDemoCategories_CategoryId", oracleDemoItemsTable, oracleDemoCategoriesTable,
                new[] { categoryIdColumn },
                oracleDemoCategoriesTable.FindUniqueConstraint("PK_OracleDemoCategories")!, ReferentialAction.SetNull);
            fK_OracleDemoItems_OracleDemoCategories_CategoryId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<int, int>(fK_OracleDemoItems_OracleDemoCategories_CategoryId));
            var fK_OracleDemoItems_OracleDemoCategories_CategoryIdFk = RelationalModel.GetForeignKey(this,
                "DotNetMinimalAPI.Models.OracleDemoItem",
                new[] { "CategoryId" },
                "DotNetMinimalAPI.Models.OracleDemoCategory",
                new[] { "Id" });
            fK_OracleDemoItems_OracleDemoCategories_CategoryId.MappedForeignKeys.Add(fK_OracleDemoItems_OracleDemoCategories_CategoryIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_OracleDemoItems_OracleDemoCategories_CategoryIdFk).Add(fK_OracleDemoItems_OracleDemoCategories_CategoryId);
            oracleDemoItemsTable.ForeignKeyConstraints.Add(fK_OracleDemoItems_OracleDemoCategories_CategoryId);
            oracleDemoCategoriesTable.ReferencingForeignKeyConstraints.Add(fK_OracleDemoItems_OracleDemoCategories_CategoryId);
            return relationalModel.MakeReadOnly();
        }
    }
}
