// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using DotNetMinimalAPI.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DotNetMinimalAPI.CompiledModels
{
    public static class OracleDemoItemUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(OracleDemoItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CategoryId>k__BackingField")]
        public static extern ref int? CategoryId(OracleDemoItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(OracleDemoItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(OracleDemoItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(OracleDemoItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Category>k__BackingField")]
        public static extern ref OracleDemoCategory Category(OracleDemoItem @this);
    }
}
