// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using DotNetMinimalAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Oracle.EntityFrameworkCore.Metadata;
using Oracle.EntityFrameworkCore.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DotNetMinimalAPI.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class OracleDemoItemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "DotNetMinimalAPI.Models.OracleDemoItem",
                typeof(OracleDemoItem),
                baseEntityType,
                propertyCount: 5,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(OracleDemoItem).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OracleDemoItem).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Id(instance),
                bool (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                OracleDemoItem (OracleDemoItem instance, int value) =>
                {
                    OracleDemoItemUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                OracleDemoItem (OracleDemoItem instance, int value) =>
                {
                    OracleDemoItemUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && OracleDemoItemUnsafeAccessors.Id(((OracleDemoItem)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : OracleDemoItemUnsafeAccessors.Id(((OracleDemoItem)(entry.Entity))))),
                int (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.Id(((OracleDemoItem)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = OracleInt32TypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            var categoryId = runtimeEntityType.AddProperty(
                "CategoryId",
                typeof(int?),
                propertyInfo: typeof(OracleDemoItem).GetProperty("CategoryId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OracleDemoItem).GetField("<CategoryId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            categoryId.SetGetter(
                int? (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.CategoryId(instance),
                bool (OracleDemoItem instance) => !(OracleDemoItemUnsafeAccessors.CategoryId(instance).HasValue));
            categoryId.SetSetter(
                OracleDemoItem (OracleDemoItem instance, int? value) =>
                {
                    OracleDemoItemUnsafeAccessors.CategoryId(instance) = value;
                    return instance;
                });
            categoryId.SetMaterializationSetter(
                OracleDemoItem (OracleDemoItem instance, int? value) =>
                {
                    OracleDemoItemUnsafeAccessors.CategoryId(instance) = value;
                    return instance;
                });
            categoryId.SetAccessors(
                int? (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<int?>(1) : (entry.FlaggedAsTemporary(1) && !(OracleDemoItemUnsafeAccessors.CategoryId(((OracleDemoItem)(entry.Entity))).HasValue) ? entry.ReadTemporaryValue<int?>(1) : OracleDemoItemUnsafeAccessors.CategoryId(((OracleDemoItem)(entry.Entity))))),
                int? (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.CategoryId(((OracleDemoItem)(entry.Entity))),
                int? (IInternalEntry entry) => entry.ReadOriginalValue<int?>(categoryId, 1),
                int? (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int?>(categoryId, 1));
            categoryId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            categoryId.TypeMapping = OracleInt32TypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v));
            categoryId.SetCurrentValueComparer(new EntryCurrentValueComparer<int?>(categoryId));
            categoryId.SetComparer(new NullableValueComparer<int>(categoryId.TypeMapping.Comparer));
            categoryId.SetKeyComparer(new NullableValueComparer<int>(categoryId.TypeMapping.KeyComparer));
            categoryId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(OracleDemoItem).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OracleDemoItem).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.CreatedAt(instance),
                bool (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                OracleDemoItem (OracleDemoItem instance, DateTime value) =>
                {
                    OracleDemoItemUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                OracleDemoItem (OracleDemoItem instance, DateTime value) =>
                {
                    OracleDemoItemUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.CreatedAt(((OracleDemoItem)(entry.Entity))),
                DateTime (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.CreatedAt(((OracleDemoItem)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 2),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = OracleDateTimeTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v));
            createdAt.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(OracleDemoItem).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OracleDemoItem).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            description.SetGetter(
                string (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Description(instance),
                bool (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                OracleDemoItem (OracleDemoItem instance, string value) =>
                {
                    OracleDemoItemUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                OracleDemoItem (OracleDemoItem instance, string value) =>
                {
                    OracleDemoItemUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.Description(((OracleDemoItem)(entry.Entity))),
                string (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.Description(((OracleDemoItem)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = OracleStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "NVARCHAR2(2000)",
                    size: 2000,
                    unicode: true,
                    dbType: System.Data.DbType.String),
                storeTypePostfix: StoreTypePostfix.Size);
            description.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(OracleDemoItem).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OracleDemoItem).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            name.SetGetter(
                string (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Name(instance),
                bool (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                OracleDemoItem (OracleDemoItem instance, string value) =>
                {
                    OracleDemoItemUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                OracleDemoItem (OracleDemoItem instance, string value) =>
                {
                    OracleDemoItemUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.Name(((OracleDemoItem)(entry.Entity))),
                string (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.Name(((OracleDemoItem)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = OracleStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "NVARCHAR2(2000)",
                    size: 2000,
                    unicode: true,
                    dbType: System.Data.DbType.String),
                storeTypePostfix: StoreTypePostfix.Size);
            name.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { categoryId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CategoryId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            var category = declaringEntityType.AddNavigation("Category",
                runtimeForeignKey,
                onDependent: true,
                typeof(OracleDemoCategory),
                propertyInfo: typeof(OracleDemoItem).GetProperty("Category", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OracleDemoItem).GetField("<Category>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            category.SetGetter(
                OracleDemoCategory (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Category(instance),
                bool (OracleDemoItem instance) => OracleDemoItemUnsafeAccessors.Category(instance) == null);
            category.SetSetter(
                OracleDemoItem (OracleDemoItem instance, OracleDemoCategory value) =>
                {
                    OracleDemoItemUnsafeAccessors.Category(instance) = value;
                    return instance;
                });
            category.SetMaterializationSetter(
                OracleDemoItem (OracleDemoItem instance, OracleDemoCategory value) =>
                {
                    OracleDemoItemUnsafeAccessors.Category(instance) = value;
                    return instance;
                });
            category.SetAccessors(
                OracleDemoCategory (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.Category(((OracleDemoItem)(entry.Entity))),
                OracleDemoCategory (IInternalEntry entry) => OracleDemoItemUnsafeAccessors.Category(((OracleDemoItem)(entry.Entity))),
                null,
                OracleDemoCategory (IInternalEntry entry) => entry.GetCurrentValue<OracleDemoCategory>(category));
            category.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            var items = principalEntityType.AddNavigation("Items",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<OracleDemoItem>),
                propertyInfo: typeof(OracleDemoCategory).GetProperty("Items", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OracleDemoCategory).GetField("<Items>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            items.SetGetter(
                ICollection<OracleDemoItem> (OracleDemoCategory instance) => OracleDemoCategoryUnsafeAccessors.Items(instance),
                bool (OracleDemoCategory instance) => OracleDemoCategoryUnsafeAccessors.Items(instance) == null);
            items.SetSetter(
                OracleDemoCategory (OracleDemoCategory instance, ICollection<OracleDemoItem> value) =>
                {
                    OracleDemoCategoryUnsafeAccessors.Items(instance) = value;
                    return instance;
                });
            items.SetMaterializationSetter(
                OracleDemoCategory (OracleDemoCategory instance, ICollection<OracleDemoItem> value) =>
                {
                    OracleDemoCategoryUnsafeAccessors.Items(instance) = value;
                    return instance;
                });
            items.SetAccessors(
                ICollection<OracleDemoItem> (IInternalEntry entry) => OracleDemoCategoryUnsafeAccessors.Items(((OracleDemoCategory)(entry.Entity))),
                ICollection<OracleDemoItem> (IInternalEntry entry) => OracleDemoCategoryUnsafeAccessors.Items(((OracleDemoCategory)(entry.Entity))),
                null,
                ICollection<OracleDemoItem> (IInternalEntry entry) => entry.GetCurrentValue<ICollection<OracleDemoItem>>(items));
            items.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            items.SetCollectionAccessor<OracleDemoCategory, ICollection<OracleDemoItem>, OracleDemoItem>(
                ICollection<OracleDemoItem> (OracleDemoCategory entity) => OracleDemoCategoryUnsafeAccessors.Items(entity),
                (OracleDemoCategory entity, ICollection<OracleDemoItem> collection) => OracleDemoCategoryUnsafeAccessors.Items(entity) = ((ICollection<OracleDemoItem>)collection),
                (OracleDemoCategory entity, ICollection<OracleDemoItem> collection) => OracleDemoCategoryUnsafeAccessors.Items(entity) = ((ICollection<OracleDemoItem>)collection),
                ICollection<OracleDemoItem> (OracleDemoCategory entity, Action<OracleDemoCategory, ICollection<OracleDemoItem>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<OracleDemoCategory, ICollection<OracleDemoItem>, OracleDemoItem>(entity, setter),
                ICollection<OracleDemoItem> () => ((ICollection<OracleDemoItem>)(((ICollection<OracleDemoItem>)(new HashSet<OracleDemoItem>(ReferenceEqualityComparer.Instance))))));
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var categoryId = runtimeEntityType.FindProperty("CategoryId");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var description = runtimeEntityType.FindProperty("Description");
            var name = runtimeEntityType.FindProperty("Name");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            var category = runtimeEntityType.FindNavigation("Category");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((OracleDemoItem)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int?, DateTime, string, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<int?>(categoryId) == null ? null : ((ValueComparer<int?>)(((IProperty)categoryId).GetValueComparer())).Snapshot(source.GetCurrentValue<int?>(categoryId))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, int?>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int)), (default(int? ) == null ? null : ((ValueComparer<int?>)(((IProperty)categoryId).GetValueComparer())).Snapshot(default(int? )))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int, int?>(default(int), default(int? )))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((OracleDemoItem)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int?, object>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<int?>(categoryId) == null ? null : ((ValueComparer<int?>)(((IProperty)categoryId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int?>(categoryId))), source.GetCurrentValue<OracleDemoCategory>(category))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 5,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 5,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "OracleDemoItems");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
