// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using DotNetMinimalAPI.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DotNetMinimalAPI.CompiledModels
{
    public static class OracleDemoCategoryUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(OracleDemoCategory @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(OracleDemoCategory @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(OracleDemoCategory @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Items>k__BackingField")]
        public static extern ref ICollection<OracleDemoItem> Items(OracleDemoCategory @this);
    }
}
